print("IF YOU SEE THIS MESSAGE YOU DID NOT PROPERLY INSTALL THE SNIPER.")
print("THE VIDEO / WRITTEN GUIDE YOU WERE FOLLOWING WAS OUT OF DATE")
print("GO TO THE README @ https://mcsniperpy.com/git AND FOLLOW THE INSTRUCTIONS THERE")
input("")
